# Generated by Django 5.0.1 on 2025-11-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_subscription_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(help_text="File MIME type", max_length=255),
        ),
    ]
